### ISSUE TITLE
Error: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by Missgoodluck** [MarcDrexler/3Commas.BulkEditor#12]
Hi can you help me, when i try to run Bulk editor , the error shows up 
http://joxi.ru/Drl0n5btyGJavr

**Comment by MarcDrexler** [comment]
Hi,
it looks like you are using Windows 7 or even Vista.
That OS is no longer receiving security updates and I _think_ this is the problem here. Both TLS 1.0 and 1.1 are deprecated on March 31, 2020. You should consider migrating your machine to a more updated operative system in the long term.

There are a few articles that deal with the topic and maybe you can enable TLS 1.2:
This one for example (haven't tested it): https://johnhaller.com/useful-stuff/enable-tls-1.1-and-1.2-on-windows-vista
(Windows uses Internet Explorer Settings in the background for those requests. That's why it's about Internet Explorer)

**Comment by Missgoodluck** [comment]
Cool that helped now its working thank you for your help
