### ISSUE TITLE
question 3commas bulk editor

### ISSUE THREAD

**Issue by Murzels** [MarcDrexler/3Commas.BulkEditor#43]
hi greets,

is it possible to add a option for add funds? market price adding manual safty order?

nice work 

have a nice weekend

**Comment by MarcDrexler** [comment]
Hi,

I have just added a simple method to bulk add funds.

have a nice weekend too! :)

**Comment by Murzels** [comment]
hi thanks For adding "Add funds"

but Now i Need Add Funds € also 😊😘

Marc ***@***.***> schrieb am Sa., 13. März 2021, 01:45:

**Comment by MarcDrexler** [comment]
The deals quote currency actually doesn’t matter. Because in a bulk add funds operation, you could have different quote currencies and the idea is that the user can simply choose between USD or BTC. It is only to help the user, some prefer BTC, some prefer USD (or EUR) ;)
The program will then calculate the entered amount in the specific quote currency for each deal.
I can add an option for €. But you already can use it even if your bot‘s quote currency is €.

**Comment by Murzels** [comment]
€ only function would be nice 😊

thx and nice weekend

Marc ***@***.***> schrieb am Sa., 13. März 2021, 19:50:
