### ISSUE TITLE
Missing Leverage fields and stop loss enable/disable

### ISSUE THREAD

**Issue by cubissimo** [MarcDrexler/3Commas.BulkEditor#5]
Hi! just to report some missing fields that would be great to have

- Leverage Size
- StopLoss Enable/Disable

Tks for this awesome tool

**Comment by MarcDrexler** [comment]
Hi! 
Fields for Stop Loss are already there.
If you want to disable it, simply set the percentage to zero.

I have added Fields for Leverage Type and Custom Value:

![image](https://user-images.githubusercontent.com/16029585/94405443-d8c9c980-0170-11eb-8e0c-90ac2b1d801c.png)

**Comment by cubissimo** [comment]
Great! I thought that put 0% on stoploss will in fact stop at 0%.. like a neutral stoploss position..

Tks youre awesome!

**Comment by MarcDrexler** [comment]
![image](https://user-images.githubusercontent.com/16029585/94438927-0712cd80-01a0-11eb-9b74-764095185906.png)

That switch you know from 3c GUI, is actually not available via API. Everything is done via percentage value.

But I might add something similar later because it would make it clear to everyone whether something is on or off. Thanks! 👍
